### ISSUE TITLE
Multiple tasks with description from draft

### ISSUE THREAD

**Issue by ericwass** [FlohGro-dev/Draftist#1]
Hey,
Thank you for making these. They're amazing. There's one thing I'd love to be able to do and I can't see an action that will do it. I'm probably missing something, so I'd love your input.

One of my best workflows is using Superhuman to copy a link to an email then create an action regarding that email with the description being the link back to the original email. That way I can clear out my inbox pretty rapidly and move it all over to Todoist.

What I want to do is do a quick brain dump into Drafts of multiple tasks each with their own settings (written our in Drafts, not a prompt from the action) and include the Superhuman link in the description. So, for instance, in a single draft I could write...

```
Follow up on contractor bid #remodel tomorrow 1p p2
superhuman://inbox/other/thread/xxxxxxxxx#app

Reschedule meeting with Sam #interviews Friday 10am p1
superhuman://inbox/other/thread/1xxxxxxx#app

Ask accountant about invoice next Monday 10am
superhuman://inbox/other/thread/xxxxxxxx#app
```

...and then run an action that would create 3 separate tasks in Todoist with those email links in the description.

Is this already do-able? Could an action be altered to handle it? It would be super useful.

Thanks.

**Comment by FlohGro-dev** [comment]
Hi @ericwass,

thanks for your request.
I have two thoughts on that:

1) an already possible solution.
you can nearly achieve what you are describing right now with the current [quickadd lines from draft](https://github.com/FlohGro-dev/Draftist/blob/main/Action%20Descriptions.md#quick-add-lines-from-draft) Action if you make a small change in the task formatting. You can include the link to the e-mail directly in the tasks content formatted as links when you use markdown links to the e-mails: "[task content](link-to-email)"
I do this all the time since I don't need to open the description - instead I have a clickable link. Given your example above this would look like this:

```
[Follow up on contractor bid](superhuman://inbox/other/thread/xxxxxxxxx#app) #remodel tomorrow 1p p2
[Reschedule meeting with Sam](superhuman://inbox/other/thread/1xxxxxxx#app) #interviews Friday 10am p1
[Ask accountant about invoice](superhuman://inbox/other/thread/xxxxxxxx#app) next Monday 10am
```
It doesn't matter if you have empty lines in between 

2) An addition to the action set.
Its possible to create a new Action which uses e.g. a custom separator (in your case an empty line) between tasks with descriptions. I can add this of course. The only problem then would be that you'd loose the quick add functionality (like you described the settings for the task written in the draft not in prompts. This is a limitation of the quick add API.

I think the solution 1) is much more what you would like to do and maybe eases your workflow

**Comment by ericwass** [comment]
That’s great. I’ll try it. Thank you

**Comment by FlohGro-dev** [comment]
@ericwass did this "fix" your issue? if yes I'll close this one :) otherwise please let me know how I can improve Draftist to fit your needs :)

**Comment by FlohGro-dev** [comment]
dont know if superhuman also supports that but with the stock mail app you can drag and drop mails into drafts app (also on iOS - just drag an e-mail, hold it, switch apps and drop it into the Draft).
This will create a URL to the E-Mail.
I'm not sure if superhuman supports that, too.

Additionally you could create an Action to speed up creating the link brackets around that superhuman url (there alrady are "link" actions in the directory - just find one that fits for you
